language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate:fresh --seed
  - composer update --prefer-dist


before_install:
  - mysql -e 'CREATE DATABASE homestead;'
  - npm install
  - npm run dev
script:
  #- phpunit --coverage-clover coverage.xml
  - phpunit

after_script:
  # upload coverage.xml file to Coveralls to analyze it
  # minimal required coverage is set to 80+ %
  # - wget https://github.com/satooshi/php-coveralls/releases/download/v2.1.0/coveralls.phar
  # - php coveralls.phar --verbose

services:
  - maria
  - neo4j

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

dist: trusty

sudo: required

notifications:
email: false
