language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer update --prefer-dist
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE homestead;'
  - npm install
  - npm run dev
script:
  - phpunit

services:
  - maria-db

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

dist: trusty

sudo: required

notifications:
email: false
