version: '3'

services:
  genealogy-server:
    build: ./provisioning
    image: modulargenealogy
    depends_on:
      - mysql
      - neo4j
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7@sha256:f568db3bdc3226cc28e4b148e6b9fd4e68d9c42e97a82be671bbe9eeb37ab1d5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx:latest@sha256:1f9c00b4c95ef931afa097823d902e7602aebc3ec5532e907e066978075ca3e0
    ports:
      - "80:80"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - genealogy-server

  neo4j:
    image: neo4j:latest@sha256:d65e62b9e006fc9d246847c12de7a37dc65a079564ad6a1608f73dbdc9d5051b
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./db/dbms:/data/dbms
